[package]
name = "monkey-printer"
description = "With an infinite monkeys you could write Shakespeare"
license = "MIT"
version = "0.1.0"
edition = "2021"
[workspace]

[dependencies]
indicatif = "0.17"
tokio = { version = "1", features = ["full"] }
futures = "0.3"